Repository terraform-providers/terraform-provider-bitbucket, pull requests merged in 2020-08, with the labels that each got.

#54 Typo: secuired -> secured
  website/docs/r/repository_variable.html.markdown
Labels: documentation, size/XS

#60 Support for deployment and variables
  bitbucket/provider.go
  bitbucket/resource_deployment.go
  bitbucket/resource_deployment_test.go
  bitbucket/resource_deployment_variable.go
  bitbucket/resource_deployment_variable_test.go
  bitbucket/resource_repository_variable.go
  website/docs/r/deployment.html.markdown
  website/docs/r/deployment_variable.html.markdown
Labels: documentation, size/XL

#65 Update branch_restriction.html.markdown
  website/docs/r/branch_restriction.html.markdown
Labels: documentation, size/XS

#52 Branch restriction `require_default_reviewer_approvals_to_merge` is n…
  bitbucket/resource_branch_restriction.go
Labels: size/XS

#49 Removed omitempty, as it caused HTTP 400s when bools were false.
  bitbucket/resource_hook.go
  bitbucket/resource_hook_test.go
Labels: size/S
