Repository terraform-providers/terraform-provider-bitbucket, pull requests merged in 2020-01, with the labels that each got.

#46 Fix readme error 'make bin' should be 'make build' target #45
  README.md
Labels: size/XS

#22 Add bitbucket_branch_restriction resource
  bitbucket/provider.go
  bitbucket/resource_branch_restriction.go
  bitbucket/resource_branch_restriction_test.go
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  website/bitbucket.erb
  website/docs/r/branch_restriction.html.markdown
  website/docs/r/default_reviewers.html.markdown
Labels: dependencies, documentation, size/XL

#47 Refactor BitbucketClient to just Client and fix formatting and linting
  bitbucket/client.go
  bitbucket/provider.go
  bitbucket/resource_branch_restriction.go
  bitbucket/resource_branch_restriction_test.go
  bitbucket/resource_default_reviewers.go
  bitbucket/resource_hook.go
  bitbucket/resource_hook_test.go
  bitbucket/resource_repository.go
  bitbucket/resource_repository_test.go
  bitbucket/resource_repository_variable.go
Labels: size/M

#30 Added support for projects
  README.md
  bitbucket/provider.go
  bitbucket/resource_project.go
  bitbucket/resource_project_test.go
  website/docs/index.html.markdown
Labels: documentation, size/L
